ALTER TABLE DBVENDOR.EMPLOYEE
 DROP PRIMARY KEY CASCADE;
DROP TABLE DBVENDOR.EMPLOYEE CASCADE CONSTRAINTS;

CREATE TABLE DBVENDOR.EMPLOYEE
(
  EMPLOYEE_ID  NUMBER                           NOT NULL,
  LASTNAME     VARCHAR2(255 BYTE),
  FIRSTNAME    VARCHAR2(255 BYTE),
  TITLE        VARCHAR2(255 BYTE),
  BIRTH_DATE   VARCHAR2(255 BYTE),
  HIRE_DATE    VARCHAR2(255 BYTE),
  ADRESS       VARCHAR2(255 BYTE),
  CITY         VARCHAR2(255 BYTE),
  REGION       VARCHAR2(255 BYTE),
  POSTAL_CODE  VARCHAR2(255 BYTE),
  COUNTRY      VARCHAR2(255 BYTE),
  HOME_PHONE   VARCHAR2(255 BYTE),
  EXTENSION    VARCHAR2(255 BYTE),
  NOTES        VARCHAR2(255 BYTE),
  STATUS       VARCHAR2(255 BYTE),
  ACTIVE       VARCHAR2(255 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DBVENDOR.EMPLOYEE_PK ON DBVENDOR.EMPLOYEE
(EMPLOYEE_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DBVENDOR.EMPLOYEE ADD (
  CONSTRAINT EMPLOYEE_PK
 PRIMARY KEY
 (EMPLOYEE_ID)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));
